# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'BOH4M':
  name: BOH4M
  long_name: BOH4M
  description: Notes du cours BOH4M de M. Antoine
